### ISSUE TITLE
where is pretrained model?

### ISSUE THREAD

**Issue by AdamAsh2019** [utiasSTARS/pyshoe#1]
Hi thanks for releasing your wonderful work! But something unexpected happened
FileNotFoundError: [Errno 2] No such file or directory: 'results/pretrained-models/3class_vn100_200hz.pkl

**Comment by brandonwagstaff** [comment]
The pretrained model should be provided when you download the dataset by running: 

`bash download_data.sh` 

It's currently provided on our server (see ftp://128.100.201.179/2019-pyshoe/results/pretrained-models/).  Please let me know if you're still having issues with this.
