### ISSUE TITLE
unable to obtain dataset ? 

### ISSUE THREAD

**Issue by Ravindradhanapal** [utiasSTARS/pyshoe#2]
Hi,

I really appreciate STARlabs for open sourcing the foot mounted IMU dataset. 

but I was unable to obtain datasets with the help of "bash download_data.sh". its Ould be of a great help if you could help me over this. I have attached the error message below.

thanks and awaiting you response.

<img width="552" alt="Screen Shot 2020-06-19 at 11 05 53 AM" src="https://user-images.githubusercontent.com/45088025/85147737-49ca1e80-b21d-11ea-819a-821d53833570.png">

Regards,
Ravindra
University of Windsor, ON, Canada.

**Comment by domo-mr-roboto** [comment]
Ravindra, 

It looks like you're running on MacOS. The download is failing because you don't have the command 'wget' installed on your system (see the error message from line 1).  You will need to install wget using, e.g., Homebrew (https://brew.sh/).

J.

**Comment by Ravindradhanapal** [comment]
I appreciate you response! now I am able to download the dataset. 

Thanks and Regards,
Ravindra
