### ISSUE TITLE
nomenclature of variables- .mat file?

### ISSUE THREAD

**Issue by Ravindradhanapal** [utiasSTARS/pyshoe#3]
Hi StarLabs,

Good morning i would like to know the nomenclature used in .mat file and what do they represent.
Example : 
Stairs.processes_data there where variables like (imu, ts, gt_idx, gt) I can decipher that **imu** consists of 3axis accelerometer and 3-axis gyroscope, **ts**  consists of time stamp, **gt** is the ground truth. 

but coming to other hall_marker_coords.mat(T_1_i, T_ipl_i,orig_pos-ts) and for vicon(zv_vicon_opt,G_shoe_opt,gt,ts,G_ared_opt,imu,best_error,zv_amvd_opt,G_amvd_opt,zv_shoe_opt,best_detector,zv_ared_opt,zv_mbgtd_opt,trial_error,G_vicon_opt,G_mbgtd_opt)

As this would help me work better on data provided, any useful link and paper to refer is also welcomed. 

Thanks in advance.

<img width="327" alt="vicon" src="https://user-images.githubusercontent.com/45088025/85565367-114f8980-b5fd-11ea-9f1f-53ba90fe1c8d.png">
<img width="299" alt="hall_marker_coords" src="https://user-images.githubusercontent.com/45088025/85565379-13194d00-b5fd-11ea-90b8-8f6345741caf.png">
<img width="277" alt="stairs processed_data" src="https://user-images.githubusercontent.com/45088025/85565389-157ba700-b5fd-11ea-8249-7ecb63a19caa.png">

Regards,
Ravindra

**Comment by brandonwagstaff** [comment]
Please see the added readme files within the data directory for interpreting the .mat file contents.
