### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by betterpei** [utiasSTARS/pyshoe#5]
Hello, I am currently researching the topic of LSTM and zero-speed detection. I want to refer to your project, but I found that the ZV_lSTm_model.tar file is damaged and the model training process cannot be seen. Could you please update this file as soon as possible?

**Comment by brandonwagstaff** [comment]
Hello,

We would need more information in order to know what the issue is. I just did a fresh download of the models and ran the `lstm_demo` in `ins_demo.py` using Pytorch 1.4.0 without any errors.

**Comment by betterpei** [comment]
> Hello,
> 
> We would need more information in order to know what the issue is. I just did a fresh download of the models and ran the `lstm_demo` in `ins_demo.py` using Pytorch 1.4.0 without any errors.

Hello, maybe my statement is not clear. My real need is to view the LSTM model training code, which is the source code of pretrained-models/zv_lstm_model.tar. Because I want to learn about the loading of data sets, the processing of data sets, and the process of model training, instead of directly using your trained models. Can you provide the code for the trained model? I tried to decompress zv_lstm_model.tar, but it failed.

**Comment by brandonwagstaff** [comment]
Hello,

Unfortunately the training code cannot be included in this repo. The main purpose was to provide open source inertial data for comparing benchmarking new systems.

Sorry for this inconvenience.
