### ISSUE TITLE
GENERALIZING TO NEW IMUS

### ISSUE THREAD

**Issue by Nicolas-zhaos** [utiasSTARS/pyshoe#6]
hi,I read the section about generalizing to new imus  in your paper, and I want to do it, but I don't know how. Can you share more details or the code? thanks

**Comment by brandonwagstaff** [comment]
Hi There,

Unfortunately this repo does not provide training code, as its main purpose is to provide open source inertial data for benchmarking new systems. 

To generalize to a new IMU, you would have to train a new model with inertial data that has been modified (by downsampling/upsampling the frequency, or adding noise to the measurements).

Sorry for this inconvenience.
