### ISSUE TITLE
Can author or co-author share the train.py with me ?

### ISSUE THREAD

**Issue by desa001** [utiasSTARS/pyshoe#7]
Hi, recently i read your "LSTM-Based Zero-Velocity Detection"  article and downloaded your code, but I found that your code only have val part so I can't use it to retrain for a low-cost MIMU. Although I have read your article carefully in training process but still got a little confuse, I want to ask if you can share the train.py with me ?
Really thanks ~

**Comment by brandonwagstaff** [comment]
Hello,

Unfortunately the training code cannot be included in this repo. The main purpose was to provide open source inertial data for comparing benchmarking new systems.

Sorry for this inconvenience.
